"""add language

Revision ID: 17cd544456c0
Revises: f22902959a25
Create Date: 2025-06-27 22:56:39.440495

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17cd544456c0"
down_revision: str | Sequence[str] | None = "f22902959a25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("languages",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("code", sa.String(), nullable=False),
    sa.Column("file_extension", sa.String(length=10), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_languages")),
    sa.UniqueConstraint("code", name=op.f("uq_languages_code")),
    sa.UniqueConstraint("name", name=op.f("uq_languages_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("languages")
    # ### end Alembic commands ###
