"""add paste and comment models

Revision ID: e9fca36d5ae9
Revises: 17cd544456c0
Create Date: 2025-06-28 01:41:57.926183

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9fca36d5ae9"
down_revision: str | Sequence[str] | None = "17cd544456c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("pastes",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(length=100), nullable=False),
    sa.Column("content", sa.TEXT(), nullable=False),
    sa.Column("is_private", sa.Boolean(), nullable=True),
    sa.Column("url", sa.UUID(), nullable=False),
    sa.Column("views", sa.Integer(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("category_id", sa.Integer(), nullable=True),
    sa.Column("language_id", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["category_id"], ["categories.id"], name=op.f("fk_pastes_category_id_categories")),
    sa.ForeignKeyConstraint(["language_id"], ["languages.id"], name=op.f("fk_pastes_language_id_languages")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_pastes_user_id_users")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_pastes")),
    sa.UniqueConstraint("url", name=op.f("uq_pastes_url")),
    )
    op.create_table("comments",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("text", sa.Text(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("paste_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["paste_id"], ["pastes.id"], name=op.f("fk_comments_paste_id_pastes")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_comments_user_id_users")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    op.drop_table("pastes")
    # ### end Alembic commands ###
